[package]

name = "spin"
version = "0.4.8"
authors = [ "Mathijs van de Nes <git@mathijs.vd-nes.nl>",
            "John Ericson <John_Ericson@Yahoo.com>" ]
license = "MIT"
repository = "https://github.com/mvdnes/spin-rs.git"
documentation = "https://mvdnes.github.io/rust-docs/spin-rs/spin/index.html"
keywords = ["spinlock", "mutex", "rwlock"]
description = """
Synchronization primitives based on spinning.
They may contain data,
They are usable without `std`
and static initializers are available.
"""

[dependencies]
slot = "0.2.3"

[features]
const_fn = []
once = ["const_fn"]
unstable = ["const_fn", "once"]
default = ["unstable"]
